from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout, name="logout"),
    path("forgetP/", views.forget_password_view, name="forgetP"),
    path("profile/", views.profile, name="profile"),
    path("setting/", views.setting, name="setting"),
    path("approvalCenter/", views.approvalCenter, name="approvalCenter"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("owner/dashboard/", views.owner_dashboard, name="owner_dashboard"),
    path("administrator/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("manager/dashboard/", views.manager_dashboard, name="manager_dashboard"),
    path("staff/dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("analytics/", views.analytics, name="analytics"),
    path("owner/analytics/", views.owner_analytics, name="owner_analytics"),
    path("administrator/analytics/", views.admin_analytics, name="admin_analytics"),
    path("manager/analytics/", views.manager_analytics, name="manager_analytics"),
    path("staff/analytics/", views.staff_analytics, name="staff_analytics"),
    path("reports/", views.reports, name="reports"),
    path("owner/reports/", views.owner_reports, name="owner_reports"),
    path("administrator/reports/", views.admin_reports, name="admin_reports"),
    path("manager/reports/", views.manager_reports, name="manager_reports"),
    path("staff/reports/", views.staff_reports, name="staff_reports"),
    path("projects/", views.projects, name="projects"),
    path("owner/projects/", views.owner_projects, name="owner_projects"),
    path("administrator/projects/", views.admin_projects, name="admin_projects"),
    path("manager/projects/", views.manager_projects, name="manager_projects"),
    path("staff/projects/", views.staff_projects, name="staff_projects"),
    path("teams/", views.teams, name="teams"),
    path("owner/teams/", views.owner_teams, name="owner_teams"),
    path("administrator/teams/", views.admin_teams, name="admin_teams"),
    path("manager/teams/", views.manager_teams, name="manager_teams"), 
    path("staff/teams/", views.staff_teams, name="staff_teams"),
    path("requests/pending/", views.request_pending, name="request_pending"),
    path("requests/history/", views.request_history, name="request_history"),
    path("requests/approved/", views.request_approved, name="request_approved"),
    path("requests/rejected/", views.request_rejected, name="request_rejected"),
    path("requests/executed/", views.request_executed, name="request_executed"),
    path("requests/<int:pk>/", views.request_details, name="request_details"),
    path("requests/search/", views.request_search, name="request_search"),
    path("approve/manager/<int:pk>/", views.manager_approval, name="manager_approval"),
    path("approve/admin1/<int:pk>/", views.admin1_approval, name="admin1_approval"),
    path("approve/admin2/<int:pk>/", views.admin2_approval, name="admin2_approval"),
    path("statistics/", views.request_statistics, name="request_statistics"),
    path("hr/", views.hr_management, name="hr_management"),
    path("hr/search/", views.search_users, name="hr_search"),
    path("hr/request/create/", views.create_user_request, name="create_user_request"),
    path("hr/request/create/options/", views.create_user_options, name="create_user_options"),
    path("hr/profile/<int:user_id>/", views.user_profile, name="user_profile"),
    path("hr/filter-data/", views.filter_data, name="filter_data"),
    path("hr/request/<int:request_id>/cancel/", views.cancel_request, name="cancel_request"),
    path("hr/user/<int:user_id>/delete/", views.delete_user_request, name="delete_user"),
    path("hr/user/<int:user_id>/restore/", views.restore_user, name="restore_user"),
    path("hr/user/<int:user_id>/promote/", views.promote_user, name="promote_user"),
    path("hr/user/<int:user_id>/demote/", views.demote_user, name="demote_user"),
    path("hr/audit/<int:user_id>/", views.audit_log, name="audit_log"),
    path("approval/", views.approval_center, name="approval_center"),
    path("approval/history/", views.approval_history, name="approval_history"),
    path("approval/search/", views.approval_search, name="approval_search"),
    path("approval/<int:request_id>/", views.approval_request_details, name="approval_request_details"),
    path("approval/<int:request_id>/approve/", views.approve_request, name="approve_request"),
    path("approval/<int:request_id>/reject/", views.reject_request, name="reject_request"),

      # already present as 'hr_management' but can alias
    path("hr/search/", views.search_users, name="search_users"),  # already present
    path("hr/filter/", views.search_users, name="filter_users"),  # reuse search for filtering
    path("hr/profile/<int:user_id>/", views.user_profile, name="user_profile"),
    path("hr/request/<int:request_id>/edit/", views.edit_user_request, name="edit_user_request"),
    path("hr/request/<int:request_id>/update/", views.update_user_request, name="update_user_request"),
    path("hr/request/<int:request_id>/delete/", views.delete_user_request, name="delete_user_request"),
    path("hr/request/<int:request_id>/approve/", views.manager_approve_request, name="manager_approve_request"),
    path("hr/request/<int:request_id>/reject/", views.reject_request, name="reject_request"),
    path("hr/request/<int:request_id>/cancel/", views.cancel_request, name="cancel_user_request"), 

    # New endpoints
    path("hr/user/<int:user_id>/activate/", views.activate_user, name="activate_user"),
    path("hr/user/<int:user_id>/suspend/", views.suspend_user, name="suspend_user"),
    path("hr/user/<int:user_id>/transfer/staff/", views.transfer_staff, name="transfer_staff"),
    path("hr/user/<int:user_id>/transfer/manager/", views.transfer_manager, name="transfer_manager"),
    path("hr/user/<int:user_id>/history/", views.user_history, name="user_history"),
    path("hr/notifications/", views.notifications, name="notifications"),
    path("hr/timeline/<int:user_id>/", views.timeline, name="timeline"),
    path("hr/timeline/", views.timeline, name="my_timeline"),
    path("hr/filter-data/", views.filter_data, name="filter_data"),

    # Approval specific (if not already)
    path("approval/", views.approval_center, name="approval_center"),
    path("approval/history/", views.approval_history, name="approval_history"),
    path("approval/search/", views.approval_search, name="approval_search"),
    path("approval/<int:request_id>/", views.approval_request_details, name="approval_request_details"),
    path("approval/<int:request_id>/approve/", views.approve_request, name="approve_request"),
    path("approval/<int:request_id>/reject/", views.reject_request_alt, name="reject_request_alt"),

    path("hr/request/<int:request_id>/cancel/", views.cancel_request, name="cancel_request"),
    path("hr/user/<int:user_id>/delete/", views.delete_user, name="delete_user"),
    path("hr/user/<int:user_id>/restore/", views.restore_user, name="restore_user"),
    path("hr/user/<int:user_id>/promote/", views.promote_user, name="promote_user"),
    path("hr/user/<int:user_id>/demote/", views.demote_user, name="demote_user"),
    path("hr/audit/<int:user_id>/", views.audit_log, name="audit_log"),
] 