# Generated by Django 6.0.6 on 2026-07-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='permissions',
        ),
        migrations.AddField(
            model_name='manager',
            name='extraPermissions',
            field=models.ManyToManyField(blank=True, to='EIOP.permission'),
        ),
        migrations.AddField(
            model_name='staff',
            name='extraPermissions',
            field=models.ManyToManyField(blank=True, to='EIOP.permission'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='EIOP.permission')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIOP.role'),
        ),
        migrations.AddField(
            model_name='organizationadministrator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIOP.role'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIOP.role'),
        ),
    ]
