# Generated by Django 6.0.6 on 2026-07-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0002_permission_remove_manager_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseowner',
            name='enterprise',
        ),
    ]
