# Generated by Django 6.0.6 on 2026-07-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0004_remove_enterpriseowner_useraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(choices=[('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('SUSPEND_USER', 'Suspend User'), ('RESTORE_USER', 'Restore User'), ('CHANGE_ROLE', 'Change Role'), ('CHANGE_PERMISSION', 'Change Permission'), ('CHANGE_MANAGER_RANK', 'Change Manager Rank')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MANAGER_APPROVED', 'Manager Approved'), ('ADMIN1_APPROVED', 'First Admin Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('executedAt', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='EIOP.enterprise')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to='EIOP.manager')),
                ('targetManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_manager_requests', to='EIOP.manager')),
                ('targetStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_staff_requests', to='EIOP.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approverType', models.CharField(choices=[('MANAGER', 'Highest Ranked Manager'), ('ADMIN1', 'Organization Administrator #1'), ('ADMIN2', 'Organization Administrator #2')], max_length=15)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decisionDate', models.DateTimeField(auto_now_add=True)),
                ('administratorApprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to='EIOP.organizationadministrator')),
                ('managerApprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to='EIOP.manager')),
                ('approvalRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='EIOP.approvalrequest')),
            ],
            options={
                'unique_together': {('approvalRequest', 'approverType')},
            },
        ),
    ]
