# Generated by Django 6.0.6 on 2026-07-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0005_approvalrequest_approvaldecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseowner',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnterpriseOwner', to='EIOP.enterprise'),
        ),
    ]
