# Generated by Django 6.0.6 on 2026-07-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0006_enterpriseowner_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='approvaldecision',
            old_name='approvalRequest',
            new_name='approval_request',
        ),
        migrations.RenameField(
            model_name='approvaldecision',
            old_name='decisionDate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='approvaldecision',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='executedAt',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='requestType',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='targetManager',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='targetStaff',
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='admin1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='admin2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('PROMOTE_USER', 'Promote User'), ('DEMOTE_USER', 'Demote User'), ('CHANGE_ROLE', 'Change Role'), ('CHANGE_PERMISSION', 'Change Permission'), ('CHANGE_RANK', 'Change Rank')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationadministrator',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MANAGER_APPROVED', 'Manager Approved'), ('ADMIN1_APPROVED', 'Administrator 1 Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PROMOTE', 'Promote'), ('DEMOTE', 'Demote'), ('CHANGE_ROLE', 'Change Role'), ('CHANGE_PERMISSION', 'Change Permission'), ('CHANGE_RANK', 'Change Rank')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='EIOP.enterprise')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('force_password_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='approvaldecision',
            name='administratorApprover',
        ),
        migrations.RemoveField(
            model_name='approvaldecision',
            name='approverType',
        ),
        migrations.RemoveField(
            model_name='approvaldecision',
            name='managerApprover',
        ),
    ]
