# Generated by Django 6.0.6 on 2026-07-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0007_alter_approvalrequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='data',
            new_name='request_data',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_type',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ORG_ADMIN', 'Organization Administrator')], max_length=20, null=True),
        ),
    ]
