# Generated by Django 6.0.6 on 2026-07-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0008_rename_data_approvalrequest_request_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvaldecision',
            old_name='comment',
            new_name='commentss',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='user',
            new_name='actor',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='admin1_approved',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='admin2_approved',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='executed',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='manager_approved',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='EIOP.approvalrequest'),
        ),
    ]
