# Generated by Django 6.0.6 on 2026-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0009_rename_comment_approvaldecision_commentss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseowner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationadministrator',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
