# Generated by Django 6.0.6 on 2026-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0010_enterpriseowner_deleted_at_manager_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managementType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
