# Generated by Django 6.0.6 on 2026-08-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0011_alter_manager_managementtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='managementType',
        ),
    ]
