# Generated by Django 6.0.6 on 2026-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIOP', '0012_remove_manager_managementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
